-- Customer Behavior Analysis Queries
-- Microsoft SQL Server (T-SQL)
select * from customer_shopping_behavior
-- Q1. What is the total revenue generated by male vs. female customers?
SELECT
    Gender,
    SUM(Purchase_Amount_USD) AS Total_Revenue
FROM dbo.customer_shopping_behavior
GROUP BY Gender
ORDER BY Total_Revenue DESC


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT
    Customer_ID,
    Purchase_Amount_USD,
    Discount_Applied
FROM dbo.customer_shopping_behavior
WHERE Discount_Applied = 'Yes'
  AND Purchase_Amount_USD > (
        SELECT AVG(Purchase_Amount_USD)
        FROM dbo.customer_shopping_behavior
  )
ORDER BY Purchase_Amount_USD DESC;


-- Q3. Which are the top 5 products with the highest average review rating?
SELECT TOP 5
    Item_Purchased,
    ROUND(AVG(CAST(Review_Rating AS DECIMAL(10,2))), 2) AS Average_Review_Rating,
    COUNT(*) AS Total_Purchases
FROM dbo.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY Average_Review_Rating DESC;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT
    Shipping_Type,
    ROUND(AVG(CAST(Purchase_Amount_USD AS DECIMAL(10,2))), 2)
        AS Average_Purchase_Amount
FROM dbo.customer_shopping_behavior
WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type
ORDER BY Average_Purchase_Amount DESC;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
SELECT
    Subscription_Status,
    COUNT(*) AS Total_Customers,
    ROUND(AVG(CAST(Purchase_Amount_USD AS DECIMAL(10,2))), 2)
        AS Average_Spend,
    ROUND(SUM(Purchase_Amount_USD), 2) AS Total_Revenue
FROM dbo.customer_shopping_behavior
GROUP BY Subscription_Status
ORDER BY Total_Revenue DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT TOP 5
    Item_Purchased,
    COUNT(*) AS Total_Purchases,
    SUM(
        CASE
            WHEN Discount_Applied = 'Yes' THEN 1
            ELSE 0
        END
    ) AS Discounted_Purchases,
    ROUND(
        100.0 *
        SUM(
            CASE
                WHEN Discount_Applied = 'Yes' THEN 1
                ELSE 0
            END
        ) / NULLIF(COUNT(*), 0),
        2
    ) AS Discount_Rate_Percent
FROM dbo.customer_shopping_behavior
GROUP BY Item_Purchased
ORDER BY Discount_Rate_Percent DESC;



-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
WITH Customer_Segments AS
(
    SELECT
        Customer_ID,
        Previous_Purchases,
        CASE
            WHEN Previous_Purchases = 1 THEN 'New'
            WHEN Previous_Purchases BETWEEN 2 AND 10 THEN 'Returning'
            WHEN Previous_Purchases > 10 THEN 'Loyal'
            ELSE 'No Previous Purchase'
        END AS Customer_Segment
    FROM dbo.customer_shopping_behavior
)
SELECT
    Customer_Segment,
    COUNT(*) AS Number_of_Customers
FROM Customer_Segments
GROUP BY Customer_Segment
ORDER BY Number_of_Customers DESC;

-- Q8. What are the top 3 most purchased products within each category?
WITH Product_Counts AS
(
    SELECT
        Category,
        Item_Purchased,
        COUNT(*) AS Total_Purchases,
        ROW_NUMBER() OVER
        (
            PARTITION BY Category
            ORDER BY COUNT(*) DESC, Item_Purchased
        ) AS Product_Rank
    FROM dbo.customer_shopping_behavior
    GROUP BY Category, Item_Purchased
)
SELECT
    Category,
    Product_Rank,
    Item_Purchased,
    Total_Purchases
FROM Product_Counts
WHERE Product_Rank <= 3
ORDER BY Category, Product_Rank;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    Subscription_Status,
    COUNT(*) AS Repeat_Buyers
FROM dbo.customer_shopping_behavior
WHERE Previous_Purchases > 5
GROUP BY Subscription_Status
ORDER BY Repeat_Buyers DESC;



-- Q10. What is the revenue contribution of each age group?
SELECT
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END AS Age_Group,
    COUNT(*) AS Total_Customers,
    ROUND(SUM(Purchase_Amount_USD), 2) AS Total_Revenue,
    ROUND(
        100.0 * SUM(Purchase_Amount_USD) /
        NULLIF(
            (SELECT SUM(Purchase_Amount_USD)
             FROM dbo.customer_shopping_behavior), 0
        ),
        2
    ) AS Revenue_Contribution_Percent
FROM dbo.customer_shopping_behavior
GROUP BY
    CASE
        WHEN Age BETWEEN 18 AND 25 THEN '18-25'
        WHEN Age BETWEEN 26 AND 35 THEN '26-35'
        WHEN Age BETWEEN 36 AND 45 THEN '36-45'
        WHEN Age BETWEEN 46 AND 55 THEN '46-55'
        ELSE '56+'
    END
ORDER BY Total_Revenue DESC;

